Further increase heap size of install4j task from 3G to 4G (#5939)
Still seeing examples of:
"install4j: compilation failed. Reason: java.lang.OutOfMemoryError: Java heap space"

Going from 2G to 3G helped avoid the above problem considering, now moving to 4G.