Keep Junit launcher at 1.5.2 (#6121)
With higher versions, IDEA can no longer run tests and
encounters an error:

```
org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-vintage' failed to discover tests
Caused by: org.junit.platform.commons.JUnitException: Failed to parse version of junit:junit: 3.8.2
```

Co-authored-by: Ron <ron.murhammer@gmail.com>