Revert f4badc520773af6723ffd7e871165a7811a439d0 - unused methods were used
In the travis build we get a warning from property util if we do not have all the necessary reflection methods available. Without some of these methods, we get errors like this:

WARNING [Triplea start thread] UnifiedMessenger -> Could not reset property:switch subject:RulesAttachment attached to:PlayerID named:Germans with name:conditionAttachment_Units_Bonus_True
java.lang.IllegalStateException: Could not reset property:switch subject:RulesAttachment attached to:PlayerID named:Germans with name:conditionAttachment_Units_Bonus_True
	at games.strategy.util.PropertyUtil.reset(PropertyUtil.java:41)
	at games.strategy.util.PropertyUtil.set(PropertyUtil.java:30)
	at games.strategy.engine.data.ChangeAttachmentChange.perform(ChangeAttachmentChange.java:75)
	at games.strategy.engine.data.GameData.performChange(GameData.java:493)
	at games.strategy.engine.framework.ServerGame$1.gameDataChanged(ServerGame.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeSingle(EndPoint.java:162)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeMultiple(EndPoint.java:140)
	at games.strategy.engine.message.unifiedmessenger.EndPoint.invokeLocal(EndPoint.java:122)
	at games.strategy.engine.message.unifiedmessenger.UnifiedMessenger.invoke(UnifiedMessenger.java:153)
	at games.strategy.engine.message.UnifiedInvocationHandler.invoke(UnifiedInvocationHandler.java:47)
	at com.sun.proxy.$Proxy9.gameDataChanged(Unknown Source)
	at games.strategy.engine.framework.ServerGame.addChange(ServerGame.java:613)
	at games.strategy.engine.delegate.DefaultDelegateBridge.addChange(DefaultDelegateBridge.java:90)
	at games.strategy.engine.delegate.DefaultDelegateBridge.addChange(DefaultDelegateBridge.java:85)
	at games.strategy.triplea.delegate.GameDelegateBridge.addChange(GameDelegateBridge.java:73)
	at games.strategy.triplea.attachments.TriggerAttachment.triggerPlayerPropertyChange(TriggerAttachment.java:1614)
	at games.strategy.triplea.attachments.TriggerAttachment.fireTriggers(TriggerAttachment.java:241)
	at games.strategy.triplea.attachments.TriggerAttachment.collectAndFireTriggers(TriggerAttachment.java:181)
	at games.strategy.triplea.delegate.BaseTripleADelegate.triggerWhenTriggerAttachments(BaseTripleADelegate.java:97)
	at games.strategy.triplea.delegate.BaseTripleADelegate.start(BaseTripleADelegate.java:43)
	at games.strategy.triplea.delegate.AbstractMoveDelegate.start(AbstractMoveDelegate.java:42)
	at games.strategy.triplea.delegate.MoveDelegate.start(MoveDelegate.java:66)
	at games.strategy.engine.framework.ServerGame.startStep(ServerGame.java:513)
	at games.strategy.engine.framework.ServerGame.runStep(ServerGame.java:420)
	at games.strategy.engine.framework.ServerGame.startGame(ServerGame.java:272)
	at games.strategy.engine.framework.startup.launcher.LocalLauncher.launchInNewThread(LocalLauncher.java:61)
	at games.strategy.engine.framework.startup.launcher.AbstractLauncher.lambda$launch$391(AbstractLauncher.java:43)
	at java.lang.Thread.run(Thread.java:745)